spring:
  data:
    mongodb:
      host: logging-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: flowersdb
      port: 27017

server:
  context-path: /logging
  port: 5000